#!/bin/bash
#
# README
# ===========================================
# This plugin is Jstat status check for JAVA8
#
# Set export JAVA Options
# ---
# JAVA_HOME    : install java path
# JSTAT_TARGET : java process target
# JSTAT_OPTION : jstat command option
#
#
# Plugin config
# ---
#
# ```
# # vim plugin-conf.d/munin-node
# [jstat_*]
#  user root
# ```
#
# Example 1
# ---
# JDK1.8_31 ~ JDK1.8_8X Bug
# this version is jstat do not move
#
#
# Example 2
# ---
# Redhat/CentOS 7 over
#
# change service unit settings
#
# ```
# # vim /etc/systemd/system/multi-user.target.wants/munin-node.service
# PrivateTmp=false
# ```
#
# ```
# # systemctl daemon-reload
# # systemctl restart munin-node.service
# ```
#
 
# EXPORT
# -------------------------------------------
JAVA_HOME=""
JSTAT_TARGET=$(basename "$0" |awk -F\_ '{print $NF}')
JSTAT_OPTIONS="-gcmetacapacity"
 
# Check
# -------------------------------------------
 
# java check
CHECK_VERSION=$($JAVA_HOME/bin/java -version 2>&1 |awk -F\" 'NR==1{print $2}' |cut -d'_' -f 1)
if [ ! "$CHECK_VERSION" = "1.8.0" ]; then
  echo "Use java version JAVA(8) ?"
  exit 0
fi
 
# Graph Setting
# -------------------------------------------
. "$MUNIN_LIBDIR"/plugins/plugin.sh
 
if [ "$1" = "autoconf" ]; then
   echo yes
   exit 0
fi
 
if [ "$1" = "config" ]; then
 
   # Graph set
   echo "graph_title $JSTAT_TARGET JAVA Metaspace Use"
   echo 'graph_args --base 1024 -l 0'
   echo 'graph_vlabel Java Server Metaspace Usage [KB]'
   echo 'graph_category java'
   echo 'graph_info This graph JAVA Metaspace Memory.'
 
   # Lavel set
   echo 'MCMN.label MCMN'
   echo "MCMN.info The minimum capacity of the Metaspace."
   echo 'MCMN.draw LINE1'
   echo 'MCMN.min 0'
   echo 'MCMN.type GAUGE'
 
   echo 'MCMX.label MCMX'
   echo "MCMX.info The maximum capacity of the Metaspace."
   echo 'MCMX.draw LINE1'
   echo 'MCMX.min 0'
   echo 'MCMX.type GAUGE'
 
   echo 'MC.label MC'
   echo "MC.info  Metaspace. capacity"
   echo 'MC.draw LINE1'
   echo 'MC.min 0'
   echo 'MC.type GAUGE'
 
   echo 'CCSMN.label CCSMN'
   echo "CCSMN.info  The minimum capacity of the CCSS"
   echo 'CCSMN.draw LINE1'
   echo 'CCSMN.min 0'
   echo 'CCSMN.type GAUGE'
 
   echo 'CCSMX.label CCSMX'
   echo "CCSMX.info  The maximum capacity of the CCSS"
   echo 'CCSMX.draw LINE1'
   echo 'CCSMX.min 0'
   echo 'CCSMX.type GAUGE'
 
   exit 0
fi
 
# Get parameter
# -------------------------------------------
JAVA_JPS=$($JAVA_HOME/bin/jps -v |awk '/'"$JSTAT_TARGET"'/{print $1}')
if [ -z "$JAVA_JPS" ]; then
  echo "MCMN.value "
  echo "MCMX.value "
  echo "MC.value "
  echo "CCSMN.value "
  echo "CCSMX.value "
  exit 0
fi
 
JAVA_JSTAT=$($JAVA_HOME/bin/jstat "$JSTAT_OPTIONS" -t "$JAVA_JPS" 1 1)
if [ -z "$JAVA_JSTAT" ]; then
  echo "MCMN.value 0"
  echo "MCMX.value 0"
  echo "MC.value 0"
  echo "CCSMN.value 0"
  echo "CCSMX.value 0"
  exit 0
fi
 
echo "$JAVA_JSTAT" | awk \
'NR==2{
  print "MCMN.value "  $2; \
  print "MCMX.value " $3; \
  print "MC.value " $4; \
  print "CCSMN.value " $5; \
  print "CCSMX.value " $6; \
}'